### ISSUE TITLE
Inconsistent Parquet Version Metadata and Parquet Data Page Version Usage

### ISSUE THREAD

**Issue by ilya160897** [parquet-go/parquet-go#127]
I noticed an inconsistency in the Parquet file metadata generated by github.com/vc42/parquet-go and feature usage within this library while processing Parquet.

Specifically, in the file metadata, it states "Parquet version 1.0" while the library uses ```DATA_PAGE_V2 ```**by default** (a feature of Parquet 2.0).

Example:

```
File Name: /home/file.parquet
Version: 1.0
Created By: github.com/vc42/parquet-go
```

This discrepancy has led to confusion during the usage of ```parquet-go```. It would be helpful for clarity and compatibility purposes if the Parquet version in the metadata aligns with the features used during file creation.

Could this be addressed to ensure consistency between the reported Parquet version and the actual features utilized?

Thank you for your attention to this matter.

**Comment by achille-roussel** [comment]
Hello @ilya160897, thanks for reporting the issue!

Based on https://github.com/apache/arrow/blob/main/go/parquet/metadata/file.go#L122-L127, it seems like the fix would be to set the `FileMetaData.Version` field to 2 instead of 1 in https://github.com/parquet-go/parquet-go/blob/main/writer.go#L790

Could you send a pull request to fix?
