### ISSUE TITLE
The minvalue of the column statistic incorrectly ignores empty strings

### ISSUE THREAD

**Issue by Shinena1998** [parquet-go/parquet-go#130]
Hi. 
When I used the following statement `select from xxx where colume="-xxx"` to query, the written entries could not be queried. However, I changed it to `select from xxx where colume like "%-xxx"` and it could be queried. Finally, I found that this column recorded the wrong minimum value, which caused the query engine to skip the group when using =, while like is a global scan, so it can be found.

What ends up happening is that this code creates this bug

https://github.com/parquet-go/parquet-go/blob/main/writer.go#L1575
```
var existingMaxValue, existingMinValue Value

if c.columnChunk.MetaData.Statistics.MaxValue != nil && c.columnChunk.MetaData.Statistics.MinValue != nil {
        existingMaxValue = c.columnType.Kind().Value(c.columnChunk.MetaData.Statistics.MaxValue)
        existingMinValue = c.columnType.Kind().Value(c.columnChunk.MetaData.Statistics.MinValue)
}

if existingMaxValue.isNull() || c.columnType.Compare(maxValue, existingMaxValue) > 0 {
        buf := c.columnChunk.MetaData.Statistics.MaxValue[:0]
        c.columnChunk.MetaData.Statistics.MaxValue = maxValue.AppendBytes(buf)
}


if existingMinValue.isNull() || c.columnType.Compare(minValue, existingMinValue) < 0 {
        buf := c.columnChunk.MetaData.Statistics.MinValue[:0]
        // When minValue is an empty byte array (empty string), minValue.AppendBytes(buf) returns nil, causing c.columnChunk.MetaData.Statistics.MinValue to nil.
        // In the next loop, because c.columnChunk.MetaData.Statistics.MinValue is nil, existingMaxValue and existingMinValue are both nil Value, resulting in the current MinValue overwriting c.columnChunk.MetaData.Statistics.MinValue.
        c.columnChunk.MetaData.Statistics.MinValue = minValue.AppendBytes(buf)
}
```

This seems to be because the underlying data structure `minValue.AppendBytes(buf)` cannot distinguish between nil and an empty byte array. I only found that this is affected here, but I don’t know if there are similar problems elsewhere, so I am unable to fully fix this problem.

This is a very serious bug, which will cause the query engine to be unable to query data. Please fix this bug as quickly as possible!!!

Thank you so much !

**Comment by achille-roussel** [comment]
Hello @Shinena1998, thanks for reporting the bug.

> This is a very serious bug, which will cause the query engine to be unable to query data. Please fix this bug as quickly as possible!!!

I agree this looks like a serious issue; however, parquet-go is a free, open-source project maintained by volunteers and companies that can sponsor engineering time, so we don't have the resources to commit to "when" this will get fixed. As a user of this software, you are also part of the ecosystem and probably the best person to contribute a fix (because you care!).

The best course of action would be to contribute a unit test that highlights the problem. Once a test is in place, we will be able to make a fix that we are confident addresses the issue, and no regressions will reintroduce it.

If you have cycles to contribute the fix, I will be happy to provide guidance to help merge it in. Let me know!

**Comment by Shinena1998** [comment]
@achille-roussel 
I'm sorry to say "please fix it as soon as possible", I just want to express the seriousness of this problem

I've added a unit test, and a simple fix that I hope will help you understand the issue a little, or show me how to fix it elegantly.

I still have a question, for the `Value.AppendBytes([]bytes)` function, when Value is []byte{}, is `value.AppendBytes(nil) == nil` reasonable?
