### ISSUE TITLE
How to keep columns order definition ?

### ISSUE THREAD

**Issue by ocordeiro** [parquet-go/parquet-go#43]
How can I maintain the order of column definitions?
It appears to have been resolved by [PR 140](https://github.com/segmentio/parquet-go/pull/140), but I have yet to discover how to do this.

```go
package main

import (
	"fmt"

	"github.com/parquet-go/parquet-go"
)

func main() {

	group := parquet.Group{
		"C": parquet.String(), // 0
		"B": parquet.String(), // 1
		"A": parquet.String(), // 2
	}

	schema := parquet.NewSchema("runtime_schema", group)

	for i, column := range schema.Columns() {
		fmt.Println(i, column[0])
	}

	/*
		0 A
		1 B
		2 C
	*/
}
```

**Comment by KasonBraley** [comment]
I'm having the same problem. It appears that it works correctly when the schema is created with a struct definition, via `parquet.SchemaOf`, does not work when using a `parquet.Group` to create the schema. So i'm assuming https://github.com/segmentio/parquet-go/pull/140 only accounted for the struct way.

**Comment by achille-roussel** [comment]
Hello, thanks for opening the issue!

As you may have noticed, `parquet.Group` is a map type, which is why you can declare the column names as string keys. Maps in Go do not have any concept of ordering, the order of keys is even explicitly randomized when iterating so that does not allow for maintaining the order of columns. To ensure that the behavior remains deterministic, parquet-go sorts the column names of a `parquet.Group`.

However, column order can be retained when constructing a schema from a struct type instead of a `parquet.Group`. In your example, it would mean modifying the code to:
```go
type schemaType struct {
  C string
  B string
  A string
}
schema := parquet.NewSchema("runtime_schema", new(schemaType))
```

I don't know how this is used in the rest of your application, if neither of those trade-offs are useful to your use case, you might want to look at providing a custom implementation of the `parquet.Node` interface which allows you to gain finer grain control over the ordering of columns. If you do end up taking this approach, you could submit a pull request to integrate this feature to parquet-go.

**Comment by KasonBraley** [comment]
@achille-roussel that makes sense. For my use case I am able to use a struct(which I am building dynamically at runtime), so I don't have any other issue here. Thank you for the in depth explanation!

**Comment by achille-roussel** [comment]
Great! I'll close this issue then; glad to hear the existing constructs are working for you!

**Comment by achille-roussel** [comment]
Ah, I realize I may have closed this a bit prematurely, @ocordeiro let me know if the provided answer does not address your issue, we can reopen and discuss further!

**Comment by ocordeiro** [comment]
Hi @achille-roussel, my problem is the same from @KasonBraley. I need create scheme dynamically and keep the order of definition to write cols correctly.
But I found a alternative. I have created a map that correlates original order with row group.

```golang
group := parquet.Group{}

cols := ["C", "B", "A"]

for i, col := range cols {
  group[col] = parquet.Int(8)
}

schema := parquet.NewSchema("schema", group)

order := make(map[int]int)
for i, col := range cols {
  for x, pcol := range schema.Columns() {
    if col.Name == pcol[0] {
       order[i] = x
       break
    }
  }
}

builder := parquet.NewRowBuilder(group)
values := [3,2,1]

for i, v := range values {
	builder.Add(order[i], parquet.ValueOf(v))
}
pw.WriteRows([]parquet.Row{builder.Row()})

```
