### ISSUE TITLE
Documentation and/or updates to running writer_test.go

### ISSUE THREAD

**Issue by zolstein** [parquet-go/parquet-go#46]
The tests in writer_test.go seem very useful as a check of the writers. However, it relies on the `parquet-tools` command and so can pass or fail depending on environment configuration. A number of utilities called "parquet-tools" exist, and the one that I infer it's based on may be deprecated?

It would be really nice to have clear documentation of how to set up one's environment to run these tests, and if it relies on a deprecated utility it would be good to find a maintained replacement.

**Comment by achille-roussel** [comment]
Hello @zolstein!

You're correct, the situation isn't great because the version of parquet-tools we originally used to test the package has been deprecated (in favor of parquet-cli I believe), but the new tools isn't backward compatible so we would have to rewrite the tests to adapt them to the new output.

If you have cycles available to do this work, it would be an extremely valuable contribution to help maintain the project!

**Comment by zolstein** [comment]
I opened a PR here: https://github.com/parquet-go/parquet-go/pull/52

There are some limitations with using parquet-cli to analyze the files, but we can still get pretty good coverage. The PR also uncovered a bug in the way the writer aggregates rowGroup-level statistics.

**Comment by achille-roussel** [comment]
Those tests may not have been run due to the inability to install parquet-tools reliably.

**Comment by zolstein** [comment]
PR is merged, the tests run in CI, and there's at least some explanation of how to set up the tests to run in the comments.
