### ISSUE TITLE
Return error instead of panic?

### ISSUE THREAD

**Issue by hangxie** [parquet-go/parquet-go#76]
There are lots of places using `panic()` whenever there is a situation:

https://github.com/search?q=repo%3Aparquet-go%2Fparquet-go+panic&type=code

Is it possible to return error instead? So that applications are able to handle errors in a elegant way as most if not all `panic()` appeared in above search is a known issue, eg a given file is not a parquet file.

**Comment by achille-roussel** [comment]
Hello @hangxie, thanks for starting this conversation.

In the search link you shared, many of the results are in test files, in which we can keep the panics as they would never impact programs in production.

In the library, panics should be triggered for misuse of the APIs; for example, values out of valid ranges, invalid use of struct tags, etc...

Would you have a specific example of a case where the library panics due to an error that should have been handled by the application?

**Comment by hangxie** [comment]
A quick sample for this:

```
package main

import (
	"fmt"
	"os"

	parquet "github.com/parquet-go/parquet-go"
)

const fileName = "/tmp/invalid-format.parquet"

func main() {
	_ = os.Remove(fileName)
	testFile, err := os.Create(fileName)
	if err != nil {
		fmt.Printf("failed to create test file: %s\n", err.Error())
		os.Exit(1)
	}
	testFile.Close()

	localFile, err := os.Open(fileName)
	if err != nil {
		fmt.Printf("failed to open local file [%s]: %s\n", fileName, err.Error())
	}

	parquetReader := parquet.NewReader(localFile)
	if parquetReader == nil {
		fmt.Println("invalid file format")
		os.Exit(1)
	}
}
```

then

```
$ go run -trimpath .
panic: reading magic header of parquet file: EOF

goroutine 1 [running]:
github.com/parquet-go/parquet-go.NewReader({0x10297e1f8, 0x14000056070}, {0x0?, 0x102573760?, 0x140000021a0?})
	github.com/parquet-go/parquet-go@v0.18.0/reader.go:272 +0x1a8
main.main()
	main/main.go:26 +0x174
exit status 2
```

**Comment by achille-roussel** [comment]
Thanks for providing an example.

You can address this issue by first opening the file with `parquet.OpenFile`, which returns an error if the underlying data is malformed.

The `*parquet.File` can then we used as input to `parquet.NewReader` if needed.

**Comment by hangxie** [comment]
Yeah that works, thank you so much.
