### ISSUE TITLE
Corrupt parquet files due to overflow in UncompressedPageSize

### ISSUE THREAD

**Issue by stoewer** [parquet-go/parquet-go#79]
I came across an issue where parquet files written by parquet-go were found to be corrupted, leading to an inability to read them using parquet-go. The panic occurred within the `filePages.ReadPage()` function, more specifically at [`bufferPool.get(bufferSize int)`](https://github.com/parquet-go/parquet-go/blob/d42d339c3f6a0f8feb155ab93d725910c35bc98c/buffer.go#L534). 

Upon debugging, it was evident that the `bufferSize` causing the panic had the value -1926395834. The buffer size is derived from [`header.UncompressedPageSize`](https://github.com/parquet-go/parquet-go/blob/d42d339c3f6a0f8feb155ab93d725910c35bc98c/file.go#L624).

Based on my investigation, it appears that an overflow may be occurring in the conversion of the uncompressed page size value from `int` to `int32` in [writer.go](https://github.com/parquet-go/parquet-go/blob/d42d339c3f6a0f8feb155ab93d725910c35bc98c/writer.go#L1390).

**Comment by stoewer** [comment]
Stack trace for the panic:
```
github.com/parquet-go/parquet-go.(*bufferPool).get(0xbb7b80?, 0xffffffff8d2d8846?)
	/home/runner/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/buffer.go:534 +0x12d
github.com/parquet-go/parquet-go.(*Column).decompress(0xc0002589c0, {0xc00060e000, 0x92b5ed0, 0xa435d04}, 0x18cdb8?)
	/home/runner/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/column.go:542 +0x38
github.com/parquet-go/parquet-go.(*Column).decodeDictionary(0xc0002589c0, {0x77ff60?}, 0xc00018cf98?, 0x18cee8?)
	/home/runner/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/column.go:771 +0xe7
github.com/parquet-go/parquet-go.(*filePages).readDictionaryPage(0xc00026e500, 0xc0001223c0?, 0xc0001223c0?)
	/home/runner/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/file.go:615 +0x35
github.com/parquet-go/parquet-go.(*filePages).ReadPage(0xc00026e500)
	/home/runner/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/file.go:550 +0x1ce
github.com/stoewer/parquet-cli/pkg/inspect.(*ColStatCalculator).NextRow(0xc00024bd10)
	/home/runner/work/parquet-cli/parquet-cli/pkg/inspect/col_stats.go:136 +0x285
github.com/stoewer/parquet-cli/pkg/output.printTab({0x89edc0, 0xc000118020}, {0x89ffe8, 0xc00024bd10})
	/home/runner/work/parquet-cli/parquet-cli/pkg/output/output.go:91 +0x222
github.com/stoewer/parquet-cli/pkg/output.PrintTable({0x89edc0?, 0xc000118020?}, {0xc00012f960?, 0x0?}, {0x89ffe8?, 0xc00024bd10?})
	/home/runner/work/parquet-cli/parquet-cli/pkg/output/output.go:61 +0x67
main.(*colStats).Run(0xbb7260)
	/home/runner/work/parquet-cli/parquet-cli/cmd/parquet-cli/cmd_col_stats.go:27 +0x7f
reflect.Value.call({0x7a8b20?, 0xbb7260?, 0x10?}, {0x80c9cd, 0x4}, {0xc00018da50, 0x0, 0x764c96?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0x7a8b20?, 0xbb7260?, 0x7aada0?}, {0xc00018da50?, 0xc00018da50?, 0x4e5250?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/reflect/value.go:380 +0xb9
github.com/alecthomas/kong.callFunction({0x7a8b20?, 0xbb7260?, 0x18?}, 0x7b59c0?)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.8.0/callbacks.go:98 +0x40b
github.com/alecthomas/kong.callMethod({0x80c7ec, 0x3}, {0x7c5740?, 0xbb7260?, 0x3?}, {0x7a8b20?, 0xbb7260?, 0xc00018dc18?}, 0x0?)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.8.0/callbacks.go:132 +0x67
github.com/alecthomas/kong.(*Context).RunNode(0xc000164280, 0xc0001982d0, {0x0, 0x0, 0xc000168640?})
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.8.0/context.go:762 +0x845
github.com/alecthomas/kong.(*Context).Run(0x7853e0?, {0x0?, 0xc00018df00?, 0x7f2f574ed5b8?})
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.8.0/context.go:787 +0x132
main.main()
	/home/runner/work/parquet-cli/parquet-cli/cmd/parquet-cli/main.go:41 +0x15d
```

**Comment by stoewer** [comment]
The panic occurred while reading a column with strings and dictionary encoding. The column contained large values with high cardinality. I assume that this caused a dictionary to become too large.

**Comment by achille-roussel** [comment]
Hello @stoewer, thanks for the amazing investigation!

The uncompressed page size should be controlled by `config.PageBufferSize`, although this is a target and not a hard limit, so it's possible to exceed 2GiB and overflow https://github.com/parquet-go/parquet-go/blob/main/writer.go#L597

The first change we should make is to error if the writer is asked to produce a page larger than 2GiB, so we never create a corrupted file. This should be done when we [write data pages](https://github.com/parquet-go/parquet-go/blob/main/writer.go#L1365) and when we [write dictionary pages](https://github.com/parquet-go/parquet-go/blob/main/writer.go#L1460).

The next change would be to allow a more graceful handling of the case where dictionaries grow too large. The Parquet specification says that pages of a column can be _downgraded_ to the PLAIN encoding when the dictionary exceeds a given limit. We haven't implemented this logic in parquet-go due to never having encountered this problem, but it could help in your case. Keep in mind that this kind of change will likely damage the performance of your readers if the dictionary grows too large and values stop being indexed.

What you could try on your end is lowering the [maximum number of rows per group](https://github.com/parquet-go/parquet-go/blob/main/config.go#L511-L525). A new dictionary page is created for each row group; lowering the limit will result in smaller dictionaries that could fit within the page size limit.

**Comment by stoewer** [comment]
Thanks for the helpful comment. I'll prepare a PR to make sure we error instead of producing corrupted files. 

About downgrading to PLAIN: I agree that this will hurt the read performance. It will also increase the file size: In our case the compressed size of the dictionary is in the range of ~100MB while the uncompressed size is gigabytes. If downgrading to PLAIN is implemented, this should be configurable or there should be a mechanism that avoids silently degrading performance

**Comment by achille-roussel** [comment]
Hello @stoewer @joe-elliott, do you think we could close this issue since #81 was merged, or do you plan further work on this?

**Comment by stoewer** [comment]
I think it would still be interesting to implement the behavior to downgrade pages of a column to `PLAIN` encoding when the dictionary exceeds the limit. But right now I don't plan to work on this. Maybe it could be worth creating a separate feature issue for the downgrading behavior and close this one

**Comment by achille-roussel** [comment]
I opened https://github.com/parquet-go/parquet-go/issues/90 to capture the follow up, let's close this issue 👍
